// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoB8Nd_j5DrHsBL32cX5C9MtnvMYvzfbw',
    appId: '1:768454849595:web:bd1c9fc46b73bdca94181e',
    messagingSenderId: '768454849595',
    projectId: 'chat-app-15660',
    authDomain: 'chat-app-15660.firebaseapp.com',
    storageBucket: 'chat-app-15660.appspot.com',
    measurementId: 'G-BC390L6W2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNJwfPBO0K967lVZPx4Uo8TvCKowGRXQQ',
    appId: '1:768454849595:android:b9a88a2f4fb3562194181e',
    messagingSenderId: '768454849595',
    projectId: 'chat-app-15660',
    storageBucket: 'chat-app-15660.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGw0P18SXdA9sHeTTLYzjkKc1wIYoe-Vo',
    appId: '1:768454849595:ios:0ee6986cbee0acd394181e',
    messagingSenderId: '768454849595',
    projectId: 'chat-app-15660',
    storageBucket: 'chat-app-15660.appspot.com',
    iosClientId: '768454849595-v0vllfbcv1enl6tg7jp6h0v8sl6tdnlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
